version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get -y -qq update
            apt-get install -y awscli
      - deploy:
          name: Cloudformation
          command: aws cloudformation create-stack --stack-name my-first-stack --template-body file://.cloudformation/template.yml --region eu-west-1
      - deploy:
          name: Upload files
          command: aws s3 sync src s3://${MyFirstBucket} --delete
