version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get -y -qq update
            apt-get install -y awscli
      - deploy:
          name: Cloudformation
          command: |
            aws cloudformation update-stack --stack-name my-first-stack --template-body file://.cloudformation/template.yml --region eu-west-1
            aws s3 sync src s3://${S3Name} --delete
